"""ingestion tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-02

The four tables Phase 1 writes to: users, courses, documents, chunks.

Written by hand rather than autogenerated. Autogenerate emits composite foreign
keys and check constraints inconsistently, and those constraints are the point of
this migration -- they are what makes cross-tenant corruption unrepresentable
rather than merely discouraged.

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The single hardcoded user. Real auth is Phase 7; until then everything is owned
# by this row. An obviously-fake UUID so it is never mistaken for real data.
SEED_USER_ID = "00000000-0000-0000-0000-000000000001"
SEED_USER_EMAIL = "alan@rewind.local"


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("email", sa.String(255), nullable=False, unique=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
    )

    # Explicit cast: the bound parameter arrives as varchar, which Postgres will
    # not coerce to uuid on its own.
    op.execute(
        sa.text("INSERT INTO users (id, email) VALUES (CAST(:id AS uuid), :email)").bindparams(
            id=SEED_USER_ID, email=SEED_USER_EMAIL
        )
    )

    op.create_table(
        "courses",
        sa.Column(
            "id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "user_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id"),
            nullable=False,
        ),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("code", sa.String(64)),
        sa.Column("term", sa.String(64)),
        # NOT NULL: these bound Phase 3's date inference. See the model.
        sa.Column("starts_on", sa.Date, nullable=False),
        sa.Column("ends_on", sa.Date, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
    )

    op.create_table(
        "documents",
        sa.Column(
            "id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "user_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id"),
            nullable=False,
        ),
        sa.Column(
            "course_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            sa.ForeignKey("courses.id"),
            nullable=False,
        ),
        sa.Column("kind", sa.String(32), nullable=False),
        sa.Column("title", sa.String(512), nullable=False),
        sa.Column("storage_path", sa.Text, nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True)),
        sa.Column("occurred_at_source", sa.String(32)),
        sa.Column("status", sa.String(16), nullable=False, server_default=sa.text("'pending'")),
        sa.Column("page_count", sa.Integer),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        # Referenceable key for the composite FK from chunks.
        sa.UniqueConstraint("id", "user_id", name="uq_documents_id_user_id"),
        # Document identity for re-ingestion.
        sa.UniqueConstraint("user_id", "storage_path", name="uq_documents_user_id_storage_path"),
        sa.CheckConstraint(
            "kind IN ('lecture', 'assignment', 'note', 'syllabus')", name="ck_documents_kind"
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'ready', 'failed')", name="ck_documents_status"
        ),
        sa.CheckConstraint(
            "occurred_at_source IN ('parsed_syllabus', 'inferred_filename', 'manual')",
            name="ck_documents_occurred_at_source",
        ),
        sa.CheckConstraint(
            "(occurred_at IS NULL) = (occurred_at_source IS NULL)",
            name="ck_documents_occurred_at_has_source",
        ),
    )

    op.create_table(
        "chunks",
        sa.Column(
            "id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("user_id", sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("document_id", sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("embedding", Vector(1536)),
        sa.Column("page_number", sa.Integer, nullable=False),
        sa.Column("char_start", sa.Integer, nullable=False),
        sa.Column("char_end", sa.Integer, nullable=False),
        sa.Column("chunk_index", sa.Integer, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        # Ownership is pinned to the document's owner, by the database.
        sa.ForeignKeyConstraint(
            ["document_id", "user_id"],
            ["documents.id", "documents.user_id"],
            name="fk_chunks_document_id_user_id",
        ),
        sa.UniqueConstraint("id", "user_id", name="uq_chunks_id_user_id"),
        sa.UniqueConstraint("id", "document_id", name="uq_chunks_id_document_id"),
        sa.UniqueConstraint(
            "document_id", "chunk_index", name="uq_chunks_document_id_chunk_index"
        ),
        sa.CheckConstraint("page_number >= 1", name="ck_chunks_page_number_positive"),
        sa.CheckConstraint("chunk_index >= 0", name="ck_chunks_chunk_index_non_negative"),
        sa.CheckConstraint("char_start >= 0", name="ck_chunks_char_start_non_negative"),
        sa.CheckConstraint("char_end > char_start", name="ck_chunks_char_end_after_start"),
    )


def downgrade() -> None:
    op.drop_table("chunks")
    op.drop_table("documents")
    op.drop_table("courses")
    op.drop_table("users")
